version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter precache
      - flutter doctor
  build:
    commands:
      - flutter build web --release
      - cp build/web/$INDEX_FILE build/web/index.html

  post_build:
    commands:
      - echo "SERVER_BASE_URL=$SERVER_BASE_URL" > build/web/assets/.env
      - echo "GITHUB_AUTH_URL=$GITHUB_AUTH_URL" >> build/web/assets/.env
      - echo "SENTRY_URL=$SENTRY_URL" >> build/web/assets/.env
      # - |
      #   if [ -z $CLOUDFRONT_DISTRIBUTION_ID] ; then
      #     aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
      #   fi
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build/web
