version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter precache
      - flutter doctor
  build:
    commands:
      - flutter build web --release
  post_build:
    commands:
      - echo "SERVER_BASE_URL=$SERVER_BASE_URL" > .env
      - echo "GITHUB_AUTH_URL=$GITHUB_AUTH_URL" >> .env
      - echo "SENTRY_URL=$SENTRY_URL" >> .env
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build/web
